{% set version = "0.1.2" %}

package:
  name: libevalhyd
  version: {{ version }}

source:
  url: https://gitlab.irstea.fr/HYCAR-Hydro/evalhyd/evalhyd-cpp/-/archive/v{{ version }}/evalhyd-cpp-v{{ version }}.tar.gz
  sha256: 637ba5a227d890fc559fecf41a2c90ffe45629fc756e2d34ec1906b6c2a21b26

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("libevalhyd", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - ninja
  host:
    - xtl >=0.7.5
    - xtensor >=0.24.6

test:
  commands:
    - test -d ${PREFIX}/include/evalhyd                                                    # [unix]
    - test -f ${PREFIX}/include/evalhyd/evald.hpp                                          # [unix]
    - test -f ${PREFIX}/include/evalhyd/evalp.hpp                                          # [unix]
    - test -f ${PREFIX}/lib/cmake/EvalHyd/EvalHydConfig.cmake                              # [unix]
    - test -f ${PREFIX}/lib/cmake/EvalHyd/EvalHydConfigVersion.cmake                       # [unix]
    - if not exist %LIBRARY_PREFIX%\include\evalhyd\evald.hpp (exit 1)                     # [win]
    - if not exist %LIBRARY_PREFIX%\include\evalhyd\evalp.hpp (exit 1)                     # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\EvalHyd\EvalHydConfig.cmake (exit 1)         # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\EvalHyd\EvalHydConfigVersion.cmake (exit 1)  # [win]

about:
  home: https://hydrogr.github.io/evalhyd
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENCE.rst
  summary: A C++ library to evaluate streamflow predictions
  description: |
    A header-only C++ library to evaluate deterministic and 
    probabilistic streamflow predictions
  doc_url: https://hydrogr.github.io/evalhyd/cpp
  dev_url: https://gitlab.irstea.fr/HYCAR-Hydro/evalhyd/evalhyd-cpp

extra:
  recipe-maintainers:
    - fbourgin
    - ThibHlln
